export { Hero } from "./hero";
export { About } from "./about";
export { Work } from "./work";
export { Skills } from "./skills";
export { Experience } from "./experience";
export { Education } from "./education";
export { OdooExpertise } from "./odoo-expertise";
export { ComputationalEngineering } from "./computational-engineering";
export { Contact } from "./contact";
